; ============================================================
;  Weather Station — ESP-01S  (1 MB Flash, SSD1306 128×64)
; ============================================================
[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino

board_build.flash_mode = dout
; 1M flash, NO filesystem — экономим каждый байт
board_build.ldscript = eagle.flash.1m.ld

monitor_speed  = 115200
upload_speed   = 115200
upload_port    = /dev/ttyUSB1
upload_resetmethod = nodemcu

build_flags =
    -D NDEBUG
    -Os

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    gyverlibs/GyverOLED @ ^1.6.1
